/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Catalogo: typeof import('./src/components/TablaProductos.vue')['default']
    Estadisticas: typeof import('./src/components/estadisticas.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navegacion: typeof import('./src/components/navegacion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablaProductos: typeof import('./src/components/TablaProductos.vue')['default']
  }
}
